version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: empleadosapiuser
      POSTGRES_PASSWORD: empleadosAPIpassword
      POSTGRES_DB: empleadosapidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: npm start
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://empleadosapiuser:empleadosAPIpassword@db:5432/empleadosapidb
      JWT_SECRET: empleadosAPIsecret

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: