version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: empleadosapiuser
      POSTGRES_PASSWORD: empleadosAPIpassword
      POSTGRES_DB: empleadosapidb
    volumes:
      - ./backend/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - '5432:5432'
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://empleadosapiuser:empleadosAPIpassword@db:5432/empleadosapidb
    ports:
      - '3001:3001'
    depends_on:
      - db
    command: sh -c "npm install && npx prisma migrate dev --name init && npm start"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  pgdata: